language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
  code_climate:
     CODE_CLIMATE_REPO_TOKEN : process.env.CODE_CLIMATE_REPO_TOKEN
 
env:
  global:
  - PGPORT=5433


service:
  -postgresql  
 before_script:
  
  - psql -U postgres -c 'CREATE DATABASE "propertypro";'
  - psql -U postgres -f ./model/create.sql -d propertypro  
script:
 - npm run test
 

after_success:
 - npm run coverage
 - npm report-coverage
 - npm run coveralls





