language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
addons:
  code_climate:
    REPO_TOKEN : process.env.CODE_CLIMATE_REPO_TOKEN
script:
 - npm run test
 
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
after_success:
 - npm run coverage

 - npm run coveralls





