language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
addons:
  code_climate:
     CODE_CLIMATE_REPO_TOKEN : process.env.CODE_CLIMATE_REPO_TOKEN
env:
  - DATABASE_URL :process.env.process.DATABASE_URL

service:
  -postgresql     
script:
 - npm run test
 

after_success:
 - npm run coverage
 - npm report-coverage
 - npm run coveralls





