language: node_js
node_js: 
  - "stable"
addons:
  code_climate:
     CODE_CLIMATE_REPO_TOKEN : process.env.CODE_CLIMATE_REPO_TOKEN


services:
  -postgresql 
before_script:
  - npm install
  - psql -c 'create database travis_ci_test;' -U postgres
script:
 - 

after_success:
 - npm run coverage
 - npm report-coverage
 - npm run coveralls





